### ISSUE TITLE
bug: ZEO-Client on andorid

### ISSUE THREAD

**Issue by DocBO** [zopefoundation/ZEO#30] opened 2016-06-24 11:53 UTC
Maybe you are interested in the fact, that ZEO-client works on android platform (using buildozer as android build-platform) as well, but only with a bug-fix which was also discussed for windows clients years before.
I wonder why this bug-fix was not implemented up to now.
change zrpc/client.py line 456 to:
in socket.getaddrinfo(host or 'localhost', port , 0, socket.SOCK_STREAM):

best regards,
Oliver

**Comment by jimfulton** [comment] 2016-06-24 13:00
That's awesome that ZEO works on android!

I don't remember the bug fix. It probably wasn't implemented because no one was paying attention, or maybe there weren't tests, or whatever.

Note that I'm rewriting ZEO to use asyncio. I wonder if the bug exists there.  Currently, ZEO 5 hasn't been released and only works with Python 3. I plan to make a release soon. I also plan to port it to Python 2.7. Perhaps you can try it, since python-for-android seems to support Python 3.  A major benefit of ZEO 5 is SSL support, which would be wildly important for the android use case.

If ZEO 5 isn't an option, I'd entertain a pull request for ZEO 4, is it had tests.

**Comment by tseaver** [comment] 2016-06-24 14:15
This issue is basically a duplicate of #8 (and [LP bug 1004513](https://bugs.launchpad.net/zodb/+bug/1004513)).  The proposed fix narrows the result set from [`socket.getaddrinfo`](https://docs.python.org/2/library/socket.html#socket.getaddrinfo) to include only `socket.SOCK_STREAM` results.  Given that the [next statement](https://github.com/zopefoundation/ZEO/blob/a7a5fab75ac6f8ef09d4948961176ee71669a676/src/ZEO/zrpc/client.py#L460) explicitly skips any other socket types, the change seems correct "by inspection".

Coming up with a failing test seems pointless, given that we haven't worked out CI for Windows.

**Closed** 2016-06-24 16:48 UTC
